services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbestoque'
      - 'MYSQL_PASSWORD=secret23'
      - 'MYSQL_ROOT_PASSWORD=verysecret23'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    networks:
      - app-network

  java_app: # This is the service name for your Java application
    image: eclipse-temurin:21
    container_name: api_java_teste
    depends_on:
      - mysql
    volumes:
      - ./api_java_mini-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
